language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      dist: bionic
      install: ".travis/linux/deps.sh"
      script: ".travis/linux/build.sh"
      cache: ccache

    - os: osx
      osx_image: xcode10.1 # =10.13/high sierra
      install: ".travis/macos/deps.sh"
      script: ".travis/macos/build.sh"
      cache: ccache

    - os: linux
      dist: bionic
      name: "Linux MXE"
      install: ".travis/linux-mxe/deps.sh"
      script: ".travis/linux-mxe/build.sh"
      cache: ccache

deploy:
  provider: releases
  api_key:
    secure: "XjHXrtaq9VSLL/zA1BKnrFNHrDuz4WUtn9JJs0EnngUt6zjw1q4Z2suVIw4iXWXkblWLIuA+HHXbM0RsiKHvc8FLFuZWpVkV/hz/AXLEZ40Yn+hW3b3z1zaNXFotXiKC+gmJcOgVo3/BQst1dG3gmUv2IM3JhYa4I3jzR9q5AqSqWbH8B1UdpB46St7D27kGdqt6tJAHZtKmyYRP7GfgeIVrCoOrhvgpFgzrj4p2yKy5voQWulXpyRyooaGOfXMzkcFzsiZLbJhLm3BaiFUOyRINufijjeDlyX5Df05a5x6uVxTZfjLFOyfzxTPpI/fMqNoYlRqvheoMVjGAu3s+e3KvllMM4hxD2M0J6WFV6beyzJqIwgR7Z3wgac5E2RJfQYo3S4V2SlKUAxqx4KXdQAiJ3VqdlE8V6p4eyoPIQFrJpsUfUye4d5rKj/U3SOD9OP9PDqNUEzzdwxYh4V0qexHJnegw4BOHIqIS+yr/fv2thJ27/mghG6a4rqxwbhANL7B3ZUVkFh6X+lW9lqsI+HQViJj7KbrFZNsg3rN6vwtfJsEPJctdvC26Dl8+A8vJWTQwPkiMJJSqliakR2P3XPuRRvHc28Q1tqytuVEJAJvF2/yGnGWauFLtI1D1yWlfMCNHnWftFUA3pXwr3DQoc7agKiBQjS+LU+Z58gGYB7o="
  file_glob: true
  file: "build/artifacts/*"
  skip_cleanup: true
  on:
    branch:
      - "release"
      - "staging"
    tags: true

addons:
  sonarcloud:
    organization: "xmoto"
    token:
      secure: "YXD4BaijNdAUgZ4x4ed3RNMtObWavE8+tqFK4hk9dZqA6SOmwCo8mpMnWxtx/Z+7BddCQinFSnYBXtah6/1cdw102ZC3ruMNYHYFP9x1hLlocVj5vdjL+CErkRZkcuSSRJdlgUEaaSgYw5qsszF8cMXgw3p1FPXvnCY24clDJTjDKd5Km9a6h4h7FmcwCo8jwuIArvO9t/y+JFg5DwHBf+m70u2VKTXIyOAT5udPpPe0V4YrgygwCmb5uT4Df9qRWYE1r+UHXHfxoJyQ594t6C7m8L9DZTDo8QCjsZWNzu6DQ3FR2t3SABKrcy4Hjtk4FgwAw6o10KiJ/bAq5l/RpVX2Vkk2EunkAKrcWu8kup+/8OGVfkpkp9/1l3itprZ8jQDgECE1wL8q2RRxdx5dL0h+Sju10WUC5N2RZlQNs9s3KojxfvQweCOOUIj1WQL/LXwFCuDM/8Cknooz+EPKaG3w3FY7dz/N3v11I4IHi/yZisIchPwPMOvGUzwaTovA0cmrfkoiMKczpK6MhtoPKhlTLOcFPdojhnUeYaDaNuVVN3xKO9L6bslWwAWBVl/E1D11I8NaZqr/o7hJOtLetzu/rzJJRZIlOK6cdRrvIQCuUAMcSBULmgh10V4hyt45e2rSnvBHo5txQZQRnk/5W6OaRmwj5aNM5JvxPpoUwTk=" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output ninja clean; ninja
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
